# Generated by Django 5.0.6 on 2024-06-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('end_year', models.CharField(blank=True, max_length=10)),
                ('intensity', models.CharField(blank=True, max_length=10)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('insight', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('start_year', models.CharField(blank=True, max_length=255)),
                ('impact', models.CharField(blank=True, max_length=255)),
                ('added', models.CharField(blank=True, max_length=100)),
                ('published', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('relevance', models.CharField(blank=True, max_length=10)),
                ('pestle', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('likelihood', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
